### ISSUE TITLE
How to use an ES5 module with the ES6 gulp workflow?

### ISSUE THREAD

**Issue by cubissimo** [MaximAbramchuck/angular-gulp-ionic-boilerplate#12]
Tag as a question pls :)

I mean, how to automate ES5 to use together the ES6 workflow served by this starter kit?

A lot of people certainly have legacy modules ready and likely to use with their new ES6 apps.

I missed some concept here?

**Comment by MaksimAbramchuk** [comment]
We are using gulp here, so, I think that it's pretty easy task, 5 lines of code or smth like that.

**Comment by cubissimo** [comment]
i'll give a try to combine 2 tasks.. one using ES6 workflow.. and another using the old way of angularfilesort or something like that... ty..
