### ISSUE TITLE
Android app run fails

### ISSUE THREAD

**Issue by remi-lebigre** [MaximAbramchuck/angular-gulp-ionic-boilerplate#13]
Hello, 

Thanks for the great work!
I had a failure trying to run the app under android (emulator, real device, ionic serve....), because your "gulp" default task adds a keychain to www/index.html (cache purposes I guess).

Because of that, index.html is not found. It runs smooth if I remove the "-d98a01923" to www/index-d98a01923.html (whatever the keychain is)

**Comment by emersonmellado** [comment]
It's the same thing of #14 .

Please see the description I put there in order to fix it :)

**Comment by MaksimAbramchuk** [comment]
I've merged the fix for it :)
