### ISSUE TITLE
html gulp task is renaming index.html adding rev version and ionic looks for index.html to run

### ISSUE THREAD

**Issue by cubissimo** [MaximAbramchuck/angular-gulp-ionic-boilerplate#14]
When we run the `build` gulp task the index.html is renamed in dest folder `www`, adding rev version `$.rev()`, but ionic looks for exact name `index.html` to run

**Comment by emersonmellado** [comment]
I did a little change to the gulp/build.js to fix that. you can try it too:

Add this to the header:
`var rename = require("gulp-rename");`

Then, right after the clean task **(replacing the default guild task)**:

```
gulp.task('rename', function(){
  return gulp.src("./www/index-*.html")
     .pipe(rename("./index.html"))
     .pipe(gulp.dest("./www")); 
})

gulp.task('remove', function(){
  return $.del(['www/index-*.html', '!www/index.html']);
})

gulp.task('build', ['html', 'fonts', 'other'], function () {
  gulp.start('rename');
  gulp.start('remove');
});
```

**Comment by MaksimAbramchuk** [comment]
I've merged a fix for it :)
