### ISSUE TITLE
gulp-filter 3 API change breaks build

### ISSUE THREAD

**Issue by arlowhite** [MaximAbramchuck/angular-gulp-ionic-boilerplate#4]
I bumped my npm packages with ncu -u; npm update
gulp-filter went from version 2.0.2 to 3.0.1

Just FYI, the gulp-filter API has changed and this breaks the build:
https://www.npmjs.com/package/gulp-filter

In gulp/build.js
A restore option needs to be added.

``` javascript
  var htmlFilter = $.filter('*.html', {restore: true});
  var jsFilter = $.filter('**/*.js', {restore: true});
  var cssFilter = $.filter('**/*.css', {restore: true});
```

Also, remove the function call parenthesis:

``` javascript
    .pipe(jsFilter.restore)
```

Hopefully this saves you some time since it took me a while to figure out.

**Comment by MaksimAbramchuk** [comment]
@arlowhite thanks! can you please submit a pull request? :)
